"""add productos table and new fields

Revision ID: 622494f45640
Revises: 
Create Date: 2025-04-24 21:51:52.631184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622494f45640'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos_cotizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cotizacion_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('unidades', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    with op.batch_alter_table('cotizacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion_cliente', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('moneda', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotizacion', schema=None) as batch_op:
        batch_op.drop_column('moneda')
        batch_op.drop_column('direccion_cliente')

    op.drop_table('productos_cotizacion')

    # ### end Alembic commands ###
